- name: Install common packages (Ubuntu)
  # Untested if apt will actually install these!
  ansible.builtin.apt:
    name: "{{ item.name | default(item) }}"
    state: latest
  loop: "{{ common_all }}"