- tags: pre_install
  block:

    - name: Make sure all packages are up to date in Archlinux
      become: true
      pacman:
        update_cache: true
        upgrade: true
      when: ansible_distribution == "Archlinux"

    - name: Make sure all packages are up to date in Ubuntu
      become: true
      ansible.builtin.apt:
        update_cache: true
        upgrade: yes
      when: ansible_distribution == "Ubuntu"

    - name: Make sure all packages are up to date in Fedora
      become: true
      ansible.builtin.dnf5:
        name: "*"
        state: latest
      when: ansible_distribution == "Fedora"
